In [2]:
import pandas as pd
import numpy as np
from scipy import stats
df = pd.read_csv("BuyerRatio.csv");
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [4]:
df.drop(["Observed Values"], axis =1, inplace=True)
df

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [6]:
import scipy 
from scipy import stats
Chisquares_results = scipy.stats.chi2_contingency(df)
Chisquares_results

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [7]:
Chi_square = [['Test Statistic', 'p-value'], [Chisquares_results[0], Chisquares_results[1]]]

In [8]:
Chi_square

[['Test Statistic', 'p-value'], [1.595945538661058, 0.6603094907091882]]

In [ ]:
##since,0.6>0.05,null hypothesis will get into action and hence,all proportions are equal.


In [3]:
import pandas as pd
import numpy as np
df2=pd.read_csv("CustomerOrderform.csv")
df2

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
310          NaN         NaN         NaN         NaN
311          NaN         NaN         NaN         NaN
312          NaN         NaN         NaN         NaN
313          NaN         NaN         NaN         NaN
314          NaN         NaN         NaN         NaN

[315 rows x 4 columns]

In [4]:
df2=df2.dropna()
df2

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [8]:
df2.columns

Index(['Phillippines', 'Indonesia', 'Malta', 'India'], dtype='object')

In [10]:
df2.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [11]:
df2.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [12]:
df2.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [13]:
df2.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [15]:
# Make a contingency table
count=np.array([[271,267,269,280],[29,33,31,20]])
count

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [16]:
import scipy 
from scipy import stats
Chisquares_results = scipy.stats.chi2_contingency(count)# o/p is (Chi2 stats value, p_value, df, expected obsvations)
Chisquares_results

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [17]:
Chisquares_results[1]##p-value

0.2771020991233135

In [ ]:
## since .27710>.05 hence H0 i.e. null hypothesis will be accepted ie defective percentage does not vary by the 4 centers
## and hence no action will be taken


In [18]:
df3=pd.read_csv("Fantaloons.csv")
df3

Weekdays Weekend
0       Male  Female
1     Female    Male
2     Female    Male
3       Male  Female
4     Female  Female
..       ...     ...
420      NaN     NaN
421      NaN     NaN
422      NaN     NaN
423      NaN     NaN
424      NaN     NaN

[425 rows x 2 columns]

In [19]:
df3=df3.dropna()
df3

Weekdays Weekend
0       Male  Female
1     Female    Male
2     Female    Male
3       Male  Female
4     Female  Female
..       ...     ...
395   Female    Male
396   Female  Female
397   Female  Female
398   Female    Male
399   Female  Female

[400 rows x 2 columns]

In [23]:
df3.Weekdays.value_counts()

Female    287
Male      113
Name: Weekdays, dtype: int64

In [24]:
df3.Weekend.value_counts()

Female    233
Male      167
Name: Weekend, dtype: int64

In [25]:
# Make a contingency table
count2=np.array([[287,233],[113,167]])
count2

array([[287, 233],
       [113, 167]])

In [26]:
Chisquares_results = scipy.stats.chi2_contingency(count2)# o/p is (Chi2 stats value, p_value, df, expected obsvations)
Chisquares_results

(15.434065934065934,
 8.54342267020237e-05,
 1,
 array([[260., 260.],
        [140., 140.]]))

In [27]:
Chisquares_results[1]##p-value

8.54342267020237e-05

In [ ]:
## since 8.5434e-05<.05 hence Ha i.e. alternate hypothesis will be accepted ie defective percentage does vary on the  
##weekdays vs the weekend
## and hence action will be taken.